# Generated by Django 3.2.15 on 2022-08-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticdemo',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
